# -*- coding: utf-8 -*-
"""SI2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J9PQ0bxh1O-DN-KSCzIUr_-DjBfOGJZu
"""

import torch
import torch.nn as nn
import numpy as np
import torch.optim as opti
from torch.utils.data import DataLoader
from copy import deepcopy
from torch.nn import functional as F
from tqdm.notebook import tqdm
from torchvision import transforms
from torchvision.models import resnet18
from pyhessian import hessian
from utils import *
from nngeometry.metrics import FIM
from nngeometry.object import PMatKFAC, PMatDiag, PVector
from continuum.datasets import CIFAR10
from continuum.datasets import MNIST
from continuum import ClassIncremental
from continuum import InstanceIncremental
from continuum.datasets import PyTorchDataset
import torchvision
from nngeometry.object import PMatDense
import torchvision.models as models
import torch.nn.init as init

if torch.cuda.is_available():
    device = torch.device("cuda")
    print("GPU is available")
else:
    device = torch.device("cpu")
    print("GPU is not available")

import random
def set_seed(seed):
    torch.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False

set_seed(1)

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(3, 32, 3, padding=1)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(32, 64, 3, padding=1)
        self.fc1 = nn.Linear(64 * 8 * 8, 128)
        self.fc2 = nn.Linear(128, 10)

    def forward(self, x):
        x = self.pool(nn.functional.relu(self.conv1(x)))
        x = self.pool(nn.functional.relu(self.conv2(x)))
        x = x.view(-1, 64 * 8 * 8)
        x = nn.functional.relu(self.fc1(x))
        x = self.fc2(x)
        return x

# Train set
Trainset = CIFAR10(data_path="./data", download=True, train=True)
scenario1 = ClassIncremental(Trainset, increment=2)

#Test set
Testset = CIFAR10(data_path="./data", download=True, train=False)
scenario2 = ClassIncremental(Testset, increment=2)

class SynapticIntelligence:
    def __init__(self, model, dataloader, c=0.1):
        self.model = model
        self.dataloader = dataloader
        self.c = c
        self.omega = {n: torch.zeros(p.shape).to(device) for n, p in self.model.named_parameters() if p.requires_grad}
        self.init_params = {n: p.clone().detach().to(device) for n, p in self.model.named_parameters() if p.requires_grad}
        self.path_integral = {n: torch.zeros(p.shape).to(device) for n, p in self.model.named_parameters() if p.requires_grad}

    def update_omega(self):
        for name, param in self.model.named_parameters():
            if param.requires_grad:
                delta = param - self.init_params[name]
                self.omega[name] += self.path_integral[name] / (delta ** 2 + self.c)

    def compute_path_integral(self, grads):
        for name, param in self.model.named_parameters():
            if param.requires_grad:
                self.path_integral[name] += grads[name].data.clone().detach() * (param - self.init_params[name])

    def penalty(self, model):
        loss = 0
        for name, param in model.named_parameters():
            if param.requires_grad:
                delta = param - self.init_params[name]
                loss += (self.omega[name] * delta ** 2).sum()
        return loss

    def end_task(self):
        self.update_omega()
        self.init_params = {n: p.clone().detach().to(device) for n, p in self.model.named_parameters() if p.requires_grad}
        self.path_integral = {n: torch.zeros(p.shape).to(device) for n, p in self.model.named_parameters() if p.requires_grad}

def SI_Train(model, BS, optimizer, criterion, scenario1, scenario2, Lambda, epoch):
  si = None
  for task_id, taskset in enumerate(scenario1):
      model.train()
      trainLoader = DataLoader(deepcopy(taskset), batch_size=BS, shuffle=True, num_workers=2)
      for E in range(epoch):
            for inputs, labels, t in trainLoader:
                 #Zero the parameter gradients
                 optimizer.zero_grad()

                 #Forward pass
                 outputs = model(inputs.to(device))

                 #Calculate the loss
                 Loss = criterion(outputs, labels.to(device))

                 if(task_id != 0):
                     si = SynapticIntelligence(model, trainLoader)
                 if(si):
                     Loss = Loss + (Lambda * si.penalty(model) )

                 Loss = Loss.to(device)
                 Loss.backward()

                 if (si):
                     grads = {name: param.grad.clone().detach().to(device) for name, param in model.named_parameters() if param.requires_grad}
                     si.compute_path_integral(grads)

                 optimizer.step()

      #Test
      if(task_id == 4):
         return  Final_Test(scenario2, model)

      if(si):
         si.end_task()

print("SI")
A = []
for i in range(10):
    model = Net()
    model = model.to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.SGD(model.parameters(), lr=0.0001)
    A.append( SI_Train(model, BS=16, optimizer, criterion, scenario1, scenario2, Lambda=120, epoch=50) )
    print(f"Round: {i}, A: {A[i]}")

A = np.array(A)
print(A.mean())
print(A.std())